import { useEffect,useState } from "react";
import { Award,Download,Edit3,Filter,Search,Share2,Trash2,X } from "lucide-react";
import { useNavigate,useParams } from "react-router-dom";
import CertificateCanvas,{certificateBlob} from "../components/CertificateCanvas.jsx";
import Modal from "../components/Modal.jsx";
import { api } from "../services/api.js";
import { useAuth } from "../context/AuthContext.jsx";

export default function Certificates(){
 const {id}=useParams(),navigate=useNavigate(),{isAdmin}=useAuth(); const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[search,setSearch]=useState(""),[batchYear,setBatchYear]=useState(""),[course,setCourse]=useState(""),[editing,setEditing]=useState(null),[loading,setLoading]=useState(false);
 const load=()=>{const params=new URLSearchParams();if(search.trim())params.set("search",search.trim());if(batchYear)params.set("batchYear",batchYear);if(course.trim())params.set("course",course.trim());setLoading(true);return api.get("/certificates?"+params).then(r=>{setItems(r.data);if(id){const found=r.data.find(x=>x._id===id);if(found)setSelected(found);else api.get("/certificates/"+id).then(x=>setSelected(x.data));}}).finally(()=>setLoading(false))};
 useEffect(()=>{load()},[id]);
 async function download(c){const blob=await certificateBlob(c);await api.post("/certificates/"+c._id+"/download");const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=c.certificateId+".png";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 async function share(c){const blob=await certificateBlob(c),file=new File([blob],c.certificateId+".png",{type:"image/png"});if(navigator.canShare?.({files:[file]}))await navigator.share({title:"My professional certificate",text:"I earned a certificate from "+c.companyName,files:[file]});else{await navigator.clipboard.writeText(window.location.href);window.alert("Certificate link copied.");}}
 async function saveEdit(e){e.preventDefault();const {data}=await api.put("/certificates/"+editing._id,editing);setEditing(null);setSelected(data);load()}
 async function remove(c){if(!window.confirm("Remove certificate "+c.certificateId+"?"))return;await api.delete("/certificates/"+c._id);if(selected?._id===c._id)setSelected(null);load()}
 return <div className="space-y-6">
  {selected&&<section className="overflow-hidden rounded-3xl bg-gradient-to-br from-[#082b55] via-[#0b5cab] to-[#1594dc] p-5 text-white shadow-xl sm:p-9">
   <div className="mx-auto mb-6 max-w-2xl text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-white/15"><Award size={34}/></div><p className="mt-4 text-sm font-bold uppercase tracking-[.25em] text-sky-200">Achievement unlocked</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Congratulations, {selected.studentName}!</h1><p className="mt-3 text-blue-100">You passed {selected.examName} with {selected.percentage}%. Your verified certificate is ready.</p></div>
   <div className="mx-auto max-w-5xl bg-white p-2 sm:p-4"><CertificateCanvas certificate={selected}/></div>
   <div className="mt-6 flex flex-wrap justify-center gap-3"><button className="btn-primary bg-emerald-600 hover:bg-emerald-700" onClick={()=>download(selected)}><Download size={18}/> Download PNG</button><button className="btn-secondary" onClick={()=>share(selected)}><Share2 size={18}/> Share certificate</button><button className="btn-secondary" onClick={()=>setSelected(null)}>View all certificates</button></div>
  </section>}
  {!selected&&<><div><h1 className="text-2xl font-bold">{isAdmin?"Student Certifications":"My Certificates"}</h1><p className="text-sm text-slate-500">{isAdmin?"View and filter certificates issued to students.":"Your verified professional achievements in one place."}</p></div>{isAdmin&&<form className="card grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-[2fr_1fr_1.5fr_auto_auto]" onSubmit={e=>{e.preventDefault();load()}}><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className="input pl-9" placeholder="Student name, ID, or certificate ID" value={search} onChange={e=>setSearch(e.target.value)}/></label><select className="input" value={batchYear} onChange={e=>setBatchYear(e.target.value)}><option value="">All batches</option>{Array.from({length:15},(_,i)=>new Date().getFullYear()-i).map(year=><option key={year} value={year}>{year}</option>)}</select><input className="input" placeholder="Course or training" value={course} onChange={e=>setCourse(e.target.value)}/><button className="btn-primary" disabled={loading}><Filter size={16}/>{loading?"Filtering...":"Apply filters"}</button><button type="button" className="btn-secondary" onClick={()=>{setSearch("");setBatchYear("");setCourse("");setLoading(true);api.get("/certificates").then(r=>setItems(r.data)).finally(()=>setLoading(false))}}><X size={16}/>Clear</button></form>}
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(c=><article key={c._id} className="card overflow-hidden p-4"><CertificateCanvas certificate={c}/><div className="mt-4"><p className="font-bold">{c.studentName}</p><p className="text-sm text-slate-500">{c.courseName}</p>{isAdmin&&<p className="mt-1 text-xs font-medium text-slate-500">Batch: {c.batchYear||"Not assigned"} · Student ID: {c.enrollmentNumber||"--"}</p>}<p className="mt-1 font-mono text-xs text-blue-700">{c.certificateId}</p><div className="mt-4 flex flex-wrap gap-2"><button className="btn-primary" onClick={()=>{setSelected(c);navigate((isAdmin?"/admin":"/student")+"/certificates/"+c._id)}}>View</button><button className="btn-secondary" onClick={()=>download(c)}><Download size={15}/></button>{isAdmin&&<><button className="btn-secondary" onClick={()=>setEditing({...c})}><Edit3 size={15}/></button><button className="btn-secondary text-red-600" onClick={()=>remove(c)}><Trash2 size={15}/></button></>}</div>{isAdmin&&<p className="mt-3 text-xs text-slate-400">{c.downloadCount} downloads " Issued {new Date(c.issueDate).toLocaleDateString()}</p>}</div></article>)}</div>{!items.length&&<div className="card p-10 text-center text-slate-500">No certificates found.</div>}</>}
  {editing&&<Modal title="Update Certificate" onClose={()=>setEditing(null)}><form className="space-y-3" onSubmit={saveEdit}>{["studentName","courseName","examName","companyName","signatoryName"].map(k=><label key={k} className="block text-sm font-semibold capitalize">{k.replace(/([A-Z])/g," $1")}<input className="input mt-1" value={editing[k]||""} onChange={e=>setEditing({...editing,[k]:e.target.value})}/></label>)}<div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="btn-primary">Save changes</button></div></form></Modal>}
 </div>
}
